### PR TITLE
Msvc build fix (for generating git.sln)

### PR DESCRIPTION
**Pull request by PhilipOakley**
The 'msvc-build --vs' for creating a git.sln file that is readable and compilable by Visual Studio 2008 (last working version;-) had bit rotted. 

This series, on top of 1.9.5.msysgit.0 (commit/0d6f7c802) fixes most of the issues, including: the duplicate GUID, perl make dependencies, many debug improvements, and others.

It's still not perfect, but does now run properly to create a git.sln which will build without error in VS08 express ed.

Note that 'make common-cmd.h' is still required before the 'msvc-build --vs' will compile without error.

Ultimately this will be submitted to upstream Git once review feedback has been obtained, so I'm not expecting a merge (obviously), rather I'd like others to see if it works for them.

Philip

### CODE REVIEW

**Comment by sschuberth** [comment]
Something went wrong, this PR has 250+ commits from others than only you ...

**Comment by dscho** [comment]
> This series, on top of 1.9.5.msysgit.0 (commit/0d6f7c802)

Would you terribly mind switching this PR to target `maint-1.9` instead of `master`? The merge conflicts reported by BuildHive would probably go away, then.

**Comment by PhilipOakley** [comment]
I just need to work out how to do that change - any suggestions?

**Comment by PhilipOakley** [comment]
Closing this PR in favour of #318 which was the result of trying to edit this PR.

**Pull request closed without merging**
