### PR TITLE
Kb/nanosecond file times

### PR DESCRIPTION
**Pull request by kblees**
While I don't think this will "fix" issue #312 (if ther _is_ anything to fix), better file time resolution can't hurt.

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for this! Looks good to me at the first glance, but I'd like others to review as well. Ideally, this should probably go upstream right away to reach a bigger audience for review.

**Comment by kblees** [comment]
> Ideally, this should probably go upstream right away to reach a bigger audience for review.

Then I'd have to split it into a pre-fscache + post-fscache part.

**Comment by kblees** [comment]
Sent upstream, including c9352a34 Win32: make FILETIME conversion functions public.

If adopted upstream, we still need to squash the fscache.c changes into 4725fa39 Win32: add a cache below mingw's lstat and dirent implementations

**Comment by dscho** [comment]
Hey @kblees! I allowed myself to rebase this topic branch to Git for Windows 2.x and pushed it here: https://github.com/git-for-windows/git/compare/master...kb/nanosecond-file-times (it compiles, but I did not test it yet).

Would you terribly mind to close this one Pull Request, and to open a new one in the `git-for-windows` org?

**Comment by dscho** [comment]
Hmm. It seems that my rebased version of Git fails to perform basic operations... @kblees maybe you will have time to look at it?

**Comment by dscho** [comment]
Hmm. It appears that the test suite exposes some problems with my rebased branch...

**Comment by kblees** [comment]
I'm pretty much AFK right now, will look into it in two weeks. AFAIK this
topic will clash a bit with the symlinks series.
Cu Karsten
Am 19.08.2015 20:05 schrieb "dscho" <notifications@github.com>:

**Comment by dscho** [comment]
Okay, thanks for the feedback! Have a good and relaxing two weeks!

**Comment by dscho** [comment]
Sorry, I completely forgot to close this Pull Request: I forward-ported the changes to Git for Windows 2.x a long time ago (and caused quite a few problems with using Git for Windows and libgit2-based software on the same repository...).

**Pull request closed without merging**
