### PR TITLE
poll: honor the timeout on Win32

### PR DESCRIPTION
**Pull request by ethomson**
Ensure that when passing a pipe, the gnulib poll replacement will not
return 0 before the timeout has passed.

Not obeying the timeout (and merely returning 0) causes pathological
behavior when preparing a packfile for a repository and taking a
long time to do so.  If poll were to return 0 immediately, this would
cause keep-alives to get sent as quickly as possible until the packfile
was created.  Such deviance from the standard would cause megabytes (or
more) of keep-alive packets to be sent.

`GetTickCount` is used as it is efficient, stable and monotonically
increasing.  (Neither `GetSystemTime` nor `QueryPerformanceCounter` have
all three of these properties.)

### CODE REVIEW

**Comment by ethomson** [comment]
For additional background, see http://lists.gnu.org/archive/html/bug-gnulib/2014-09/msg00045.html.

Please note the updated patch later in the thread (http://lists.gnu.org/archive/html/bug-gnulib/2014-09/msg00070.html) which is what was cherry-picked here.

**Comment by dscho** [comment]
Thank you so much!

Do you want a new `1.9.5.msysgit.1` release with this?

**Comment by ethomson** [comment]
Nope!  I'm in no hurry, I'm happy to use a locally patched build.  Thanks!  :)

**Comment by dscho** [comment]
Okay, then I'll forward port this patch to the [upcoming MSys2-based Git for Windows](https://github.com/git-for-windows/git).

**Comment by kusma** [comment]
Good catch!

**Comment by t-b** [comment]
@ethomson @dscho Is this patch safe to include into maint-1.9?
If yes I would just cherry-pick without PR.
Due to the openssl security bugs I'm currently preparing a 1.9.5.msysgit.1 release.

**Comment by dscho** [comment]
@t-b yes, it is safe to pick. Thank you!

**Comment by t-b** [comment]
@dscho Thanks. I"ve picked it.

**Pull request merged**
