### PR TITLE
solve the problem:

### PR DESCRIPTION
**Pull request by cloudchou**
if we right click git gui in the git repository directory (技术), it will tell No working directory.

### CODE REVIEW

**Comment by cloudchou** [comment]
@kblees  Can you deal this pull request?

**Comment by cloudchou** [comment]
Yes @kblees  write this code patch. 
I just find the bug's reason.
Now It's okay. 
I rewrite the commit message. 
@dscho

**Comment by cloudchou** [comment]
Now it's Okay.
This is the first open source project I joined in. 
So please forgive me.  
There are so many customs I don't know.
Thank you very much for teaching me. 
@dscho

**Comment by dscho** [comment]
@cloudchou there is nothing to forgive because you did everything right: you fixed the issue, you contributed the fix, and you addressed all comments swiftly. Thank you very much!

**Pull request merged**
